language: android

android:
  components:
      - tools
      - tools
      - platform-tools
      - build-tools-30.0.2
      - android-27
      - android-P

      # Additional components
      - extra-android-m2repository

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  ./gradlew clean build check
